inherit_gem:
  rubocop-infinum: rubocop.yml

require:
  - rubocop-infinum
  - rubocop-rake

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/db/migrate/*.rb'
  NewCops: enable
